repos:
  - repo: builtin
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-json
        exclude: 'tsconfig(\..+)*\.json$'
      - id: check-toml
      - id: check-yaml
        exclude: 'pnpm-lock\.yaml$'
      - id: check-symlinks
      - id: fix-byte-order-marker
      - id: detect-private-key
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.23.1
    hooks:
      - id: zizmor
        files: (\.(github|forgejo)/(workflows/.*|dependabot\.ya?ml))|(action\.ya?ml)$
        args: [--no-progress, --offline]
  - repo: local
    hooks:
      - id: lockfile-check
        name: lockfile-check
        language: system
        entry: pnpm install --frozen-lockfile --lockfile-only
        require_serial: true
        pass_filenames: false
        files: '(package\.json$|^pnpm-workspace\.yaml$|^pnpm-lock\.yaml$)'
      - id: lint
        name: lint
        language: system
        entry: just lint
        files: '\.(ts|js|tsx)$'
        require_serial: true
        pass_filenames: false
      - id: typecheck
        name: typecheck
        language: system
        entry: just typecheck
        files: '\.(ts|tsx)$'
        require_serial: true
        pass_filenames: false
      - id: format
        name: format
        language: system
        entry: just format
        require_serial: true
        pass_filenames: false
