/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IInvoiceIdRouteImport } from './routes/i/$invoiceId'

const IInvoiceIdRoute = IInvoiceIdRouteImport.update({
  id: '/i/$invoiceId',
  path: '/i/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/i/$invoiceId': typeof IInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/i/$invoiceId': typeof IInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/i/$invoiceId': typeof IInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/i/$invoiceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/i/$invoiceId'
  id: '__root__' | '/i/$invoiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IInvoiceIdRoute: typeof IInvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/i/$invoiceId': {
      id: '/i/$invoiceId'
      path: '/i/$invoiceId'
      fullPath: '/i/$invoiceId'
      preLoaderRoute: typeof IInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IInvoiceIdRoute: IInvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
