import type { IconComponentProps } from "@web3icons/react"
import { lazy } from "react"

type LazyIconCatalog = Record<
  string,
  React.LazyExoticComponent<
    React.ForwardRefExoticComponent<
      Omit<IconComponentProps, "ref"> & React.RefAttributes<SVGSVGElement>
    >
  >
>

export const web3icons: LazyIconCatalog = {
  Token1INCH: lazy(() => import("@web3icons/react/icons/tokens/Token1INCH")),
  TokenAAVE: lazy(() => import("@web3icons/react/icons/tokens/TokenAAVE")),
  TokenACH: lazy(() => import("@web3icons/react/icons/tokens/TokenACH")),
  TokenAPE: lazy(() => import("@web3icons/react/icons/tokens/TokenAPE")),
  TokenAPFC: lazy(() => import("@web3icons/react/icons/tokens/TokenAPFC")),
  TokenARB: lazy(() => import("@web3icons/react/icons/tokens/TokenARB")),
  TokenATH: lazy(() => import("@web3icons/react/icons/tokens/TokenATH")),
  TokenAXL: lazy(() => import("@web3icons/react/icons/tokens/TokenAXL")),
  TokenAXS: lazy(() => import("@web3icons/react/icons/tokens/TokenAXS")),
  TokenBAT: lazy(() => import("@web3icons/react/icons/tokens/TokenBAT")),
  TokenBCH: lazy(() => import("@web3icons/react/icons/tokens/TokenBCH")),
  TokenBEAM: lazy(() => import("@web3icons/react/icons/tokens/TokenBEAM")),
  TokenBLUR: lazy(() => import("@web3icons/react/icons/tokens/TokenBLUR")),
  TokenBNB: lazy(() => import("@web3icons/react/icons/tokens/TokenBNB")),
  TokenBNX: lazy(() => import("@web3icons/react/icons/tokens/TokenBNX")),
  TokenBTC: lazy(() => import("@web3icons/react/icons/tokens/TokenBTC")),
  TokenCAKE: lazy(() => import("@web3icons/react/icons/tokens/TokenCAKE")),
  TokenCHEEMS: lazy(() => import("@web3icons/react/icons/tokens/TokenCHEEMS")),
  TokenCHZ: lazy(() => import("@web3icons/react/icons/tokens/TokenCHZ")),
  TokenCOMP: lazy(() => import("@web3icons/react/icons/tokens/TokenCOMP")),
  TokenCRV: lazy(() => import("@web3icons/react/icons/tokens/TokenCRV")),
  TokenDAI: lazy(() => import("@web3icons/react/icons/tokens/TokenDAI")),
  TokenDEXE: lazy(() => import("@web3icons/react/icons/tokens/TokenDEXE")),
  TokenENS: lazy(() => import("@web3icons/react/icons/tokens/TokenENS")),
  TokenETH: lazy(() => import("@web3icons/react/icons/tokens/TokenETH")),
  TokenFDUSD: lazy(() => import("@web3icons/react/icons/tokens/TokenFDUSD")),
  TokenFRAX: lazy(() => import("@web3icons/react/icons/tokens/TokenFRAX")),
  TokenFXS: lazy(() => import("@web3icons/react/icons/tokens/TokenFXS")),
  TokenGALA: lazy(() => import("@web3icons/react/icons/tokens/TokenGALA")),
  TokenGLM: lazy(() => import("@web3icons/react/icons/tokens/TokenGLM")),
  TokenGNO: lazy(() => import("@web3icons/react/icons/tokens/TokenGNO")),
  TokenGRS: lazy(() => import("@web3icons/react/icons/tokens/TokenGRS")),
  TokenGRT: lazy(() => import("@web3icons/react/icons/tokens/TokenGRT")),
  TokenGT: lazy(() => import("@web3icons/react/icons/tokens/TokenGT")),
  TokenHOT: lazy(() => import("@web3icons/react/icons/tokens/TokenHOT")),
  TokenID: lazy(() => import("@web3icons/react/icons/tokens/TokenID")),
  TokenIMX: lazy(() => import("@web3icons/react/icons/tokens/TokenIMX")),
  TokenINJ: lazy(() => import("@web3icons/react/icons/tokens/TokenINJ")),
  TokenJASMY: lazy(() => import("@web3icons/react/icons/tokens/TokenJASMY")),
  TokenJST: lazy(() => import("@web3icons/react/icons/tokens/TokenJST")),
  TokenKAVA: lazy(() => import("@web3icons/react/icons/tokens/TokenKAVA")),
  TokenKCS: lazy(() => import("@web3icons/react/icons/tokens/TokenKCS")),
  TokenKOGE: lazy(() => import("@web3icons/react/icons/tokens/TokenKOGE")),
  TokenLCX: lazy(() => import("@web3icons/react/icons/tokens/TokenLCX")),
  TokenLDO: lazy(() => import("@web3icons/react/icons/tokens/TokenLDO")),
  TokenLEO: lazy(() => import("@web3icons/react/icons/tokens/TokenLEO")),
  TokenLINK: lazy(() => import("@web3icons/react/icons/tokens/TokenLINK")),
  TokenLPT: lazy(() => import("@web3icons/react/icons/tokens/TokenLPT")),
  TokenLRC: lazy(() => import("@web3icons/react/icons/tokens/TokenLRC")),
  TokenLTC: lazy(() => import("@web3icons/react/icons/tokens/TokenLTC")),
  TokenMANA: lazy(() => import("@web3icons/react/icons/tokens/TokenMANA")),
  TokenMASK: lazy(() => import("@web3icons/react/icons/tokens/TokenMASK")),
  TokenMATIC: lazy(() => import("@web3icons/react/icons/tokens/TokenMATIC")),
  TokenMKR: lazy(() => import("@web3icons/react/icons/tokens/TokenMKR")),
  TokenMNT: lazy(() => import("@web3icons/react/icons/tokens/TokenMNT")),
  TokenMOG: lazy(() => import("@web3icons/react/icons/tokens/TokenMOG")),
  TokenMOVE: lazy(() => import("@web3icons/react/icons/tokens/TokenMOVE")),
  TokenMUSD: lazy(() => import("@web3icons/react/icons/tokens/TokenMUSD")),
  TokenMX: lazy(() => import("@web3icons/react/icons/tokens/TokenMX")),
  TokenNEXO: lazy(() => import("@web3icons/react/icons/tokens/TokenNEXO")),
  TokenOKB: lazy(() => import("@web3icons/react/icons/tokens/TokenOKB")),
  TokenOM: lazy(() => import("@web3icons/react/icons/tokens/TokenOM")),
  TokenPAXG: lazy(() => import("@web3icons/react/icons/tokens/TokenPAXG")),
  TokenPENDLE: lazy(() => import("@web3icons/react/icons/tokens/TokenPENDLE")),
  TokenPEPE: lazy(() => import("@web3icons/react/icons/tokens/TokenPEPE")),
  TokenPOL: lazy(() => import("@web3icons/react/icons/tokens/TokenPOL")),
  TokenPRIME: lazy(() => import("@web3icons/react/icons/tokens/TokenPRIME")),
  TokenPYUSD: lazy(() => import("@web3icons/react/icons/tokens/TokenPYUSD")),
  TokenQNT: lazy(() => import("@web3icons/react/icons/tokens/TokenQNT")),
  TokenRAY: lazy(() => import("@web3icons/react/icons/tokens/TokenRAY")),
  TokenRLB: lazy(() => import("@web3icons/react/icons/tokens/TokenRLB")),
  TokenROSE: lazy(() => import("@web3icons/react/icons/tokens/TokenROSE")),
  TokenRSR: lazy(() => import("@web3icons/react/icons/tokens/TokenRSR")),
  TokenSAFE: lazy(() => import("@web3icons/react/icons/tokens/TokenSAFE")),
  TokenSAND: lazy(() => import("@web3icons/react/icons/tokens/TokenSAND")),
  TokenSFP: lazy(() => import("@web3icons/react/icons/tokens/TokenSFP")),
  TokenSHIB: lazy(() => import("@web3icons/react/icons/tokens/TokenSHIB")),
  TokenSKL: lazy(() => import("@web3icons/react/icons/tokens/TokenSKL")),
  TokenSNX: lazy(() => import("@web3icons/react/icons/tokens/TokenSNX")),
  TokenSOV: lazy(() => import("@web3icons/react/icons/tokens/TokenSOV")),
  TokenSPX: lazy(() => import("@web3icons/react/icons/tokens/TokenSPX")),
  TokenSTPT: lazy(() => import("@web3icons/react/icons/tokens/TokenSTPT")),
  TokenSTRK: lazy(() => import("@web3icons/react/icons/tokens/TokenSTRK")),
  TokenSUN: lazy(() => import("@web3icons/react/icons/tokens/TokenSUN")),
  TokenSUSHI: lazy(() => import("@web3icons/react/icons/tokens/TokenSUSHI")),
  TokenSWFTC: lazy(() => import("@web3icons/react/icons/tokens/TokenSWFTC")),
  TokenT: lazy(() => import("@web3icons/react/icons/tokens/TokenT")),
  TokenTEL: lazy(() => import("@web3icons/react/icons/tokens/TokenTEL")),
  TokenTRAC: lazy(() => import("@web3icons/react/icons/tokens/TokenTRAC")),
  TokenTRX: lazy(() => import("@web3icons/react/icons/tokens/TokenTRX")),
  TokenTUSD: lazy(() => import("@web3icons/react/icons/tokens/TokenTUSD")),
  TokenTWT: lazy(() => import("@web3icons/react/icons/tokens/TokenTWT")),
  TokenUNI: lazy(() => import("@web3icons/react/icons/tokens/TokenUNI")),
  TokenUSDC: lazy(() => import("@web3icons/react/icons/tokens/TokenUSDC")),
  TokenUSDD: lazy(() => import("@web3icons/react/icons/tokens/TokenUSDD")),
  TokenUSDE: lazy(() => import("@web3icons/react/icons/tokens/TokenUSDE")),
  TokenUSDT: lazy(() => import("@web3icons/react/icons/tokens/TokenUSDT")),
  TokenWHITE: lazy(() => import("@web3icons/react/icons/tokens/TokenWHITE")),
  TokenWOO: lazy(() => import("@web3icons/react/icons/tokens/TokenWOO")),
  TokenXAUT: lazy(() => import("@web3icons/react/icons/tokens/TokenXAUT")),
  TokenXMR: lazy(() => import("@web3icons/react/icons/tokens/TokenXMR")),
  TokenXYO: lazy(() => import("@web3icons/react/icons/tokens/TokenXYO")),
  TokenYFI: lazy(() => import("@web3icons/react/icons/tokens/TokenYFI")),
  TokenZIG: lazy(() => import("@web3icons/react/icons/tokens/TokenZIG")),
  TokenZRX: lazy(() => import("@web3icons/react/icons/tokens/TokenZRX")),
}
