[[redirects]]
from = "https://bitcartcc.com/*"
to = "https://bitcart.ai/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.bitcartcc.com/*"
to = "https://www.bitcart.ai/:splat"
status = 301
force = true

[build]
publish = "./apps/landing/dist/client"
command = "BITCART_ENV=production just build --outputStyle=stream -p @bitcart/landing"
