
[build]
publish = "./apps/directory/dist/client"
command = "BITCART_ENV=production just build --outputStyle=stream -p @bitcart/directory"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
